### ISSUE TITLE
http://mirsv.com:5000/dayall 이슈

### ISSUE THREAD

**Issue by kohbwoo** [Air-Alarm/Air-Alarm-SensorServer#8]
<img width="640" alt="스크린샷 2021-09-27 오전 4 07 44" src="https://user-images.githubusercontent.com/29862835/134820936-80548019-ed44-4166-801d-93bf652d643f.png">
  "time": "2021-09-01 23:00:04" 내용중 시간 삭제하고
  "time": "2021-09-01" 까지만 보이도록 수정 필요

**Comment by SonChangHa** [comment]
함
